db-config {
  driver = "org.postgresql.Driver"
  base-url = "jdbc:postgresql://localhost:25432"
  db-name = "flightdb"
  access {
    username = "docker"
    password = "docker"
  }
  baseline = "3.0"
  thread-pool-size = 32
  clean-database = false
  logging-active = true
}
