db-config {
  driver = "org.postgresql.Driver"
  base-url = ${DB_BASE_URL}
  db-name = ${DB_NAME}
  access {
    username = ${DB_USERNAME}
    password = ${DB_PASSWORD}
  }
  thread-pool-size = 32
  clean-database = false
  logging-active = true
}
